### ISSUE TITLE
SQLite, and have a custom web frontend to categorize

### ISSUE THREAD

**Issue by nrbray** [orthecreedence/sqlite-obj#1]
Dear Andrew, 

I appreciate you are busy, does this porject include any pointers to the custom web frontend as described in your comment on ycombinator two years ago!

I have a very similar use case.  If you have any pointers for me to learn from what you did there I would be most grateful.

Best regards Nigel

orthecreedence on Apr 17, 2018 [-]I pull the transactions into SQLite, and have a custom web frontend I use to categorize them. Then for reporting, I export the whole database into a Ledger (https://www.ledger-cli.org/) file. Works great, although it's a lot of moving pieces.
--

**Comment by orthecreedence** [comment]
Hi, Nigel. The web frontend is something I haven't released anywhere and would be probably a lot of work to get to the place where I felt comfortable doing so.

The app is kind of a mishmash and I wouldn't really wish it on anyone. Here's loosely how it's architected:

- A cron job runs daily and pulls transactions from our bank using the Plaid API. I tried to do this without Plaid but banks are notoriously difficult to get non-html information out of and our bank practically leads the charge for difficulty downloading transactions
- The Plaid results are parsed into a local transactions table in SQLite that has local transactino id, Plaid transaction id, date, description/memo, src account, dst account, and some other metadata (tags/categories/etc).
- The frontend queries this db through a simple node API and generates a list of transactions that can be updated (but only in a limited set of ways because I lost steam after a while)
- Reports are generated by dumping the SQLite transactions into ledger's native format, running ledger, parsing the results, and sending back to the frontend.

Overall the entire app is super hacky and broken in a number of ways, but works enough to muddle through our personal finances with. All in all I'd much rather just use ledger directly if it were an option, but one of the requirements was a web interface so people who don't live in the command line and vim like I do can manage our finances.

Hope this helps at least a little, I'm happy to answer more specific questions if you have them.

**Comment by nrbray** [comment]
Dear Andrew,  

Thank you so much for the feedback.  Sorry I somehow missed the notification until now.  I run all my accounts double entry [1] through SQLite, but the import is ad hoc native text tsv/csv with de-duplication.  
To save time I would pull transactions from the banks using Plaid or similar and use h/ledger [2] for reporting so looking for clues via re-use where possible, and perhaps play in Rust if I am tempted to code more than the eventual time saving...

Best regards Nigel

[1] http://www.dwmbeancounter.com/ 
[2] https://github.com/simonmichael/hledger
